version: "3.8"

services:
    # Serviço do Next.js
    app:
        image: node:18-alpine
        working_dir: /app
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - "3000:3000"
        environment:
            DATABASE_URL: postgres://postgres:postgres@db:5432/tarefas_db
        depends_on:
            - db
        command: sh -c "npm install --force && npm run migrate && npm run generate && npm run seed && npm run dev"

    # Serviço do PostgreSQL
    db:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: tarefas_db
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5433:5432"

    # web:
    #     command: "sh -c 'npm run migrate && npm run generate && npm run seed && npm run dev'"

volumes:
    pgdata:
